#!/usr/bin/env bash

commit_title=$(head -n 1 "$1")

pattern="^(feat|fix|perf|docs|style|refactor|test|build|chore|ci): .+$"

if [[ ! $commit_title =~ $pattern ]]; then
  echo -e "\n\033[31m[ERROR] Неверный формат коммита!\033[0m"
  echo "--------------------------------------------------"
  echo "Твой заголовок: \"$commit_title\""
  echo -e "\nНужно так: \033[32m<тип>: <описание>\033[0m"
  echo "Допустимые типы: feat, fix, perf, docs, style, refactor, test, build, chore, ci"
  echo "Пример: chore: setup husky hooks"
  echo "--------------------------------------------------"
  exit 1
fi

echo -e "\033[32m[SUCCESS] Коммит прошел проверку.\033[0m"